name: CI 
on: [push, pull_request]
jobs: 
 lint:
   runs-on: ubuntu-latest
   startegy:
     matrix: 
       python-version: ["3.8", "3.10"]
  steps: 
  - uses: actions/checkout@v3
  - uses: action/setup-python@v4
    with:
      python-version: ${{ matrix.python-version }}
 - run: pip install black flake8
 - run: black --check .
 - run: flake8 .
 
